import Groq from "groq-sdk";
import { NextResponse, type NextRequest } from "next/server";
import { getCurrentUser } from "@/lib/auth";
import { consumeAiAction } from "@/lib/access";
import { createAdminSupabase } from "@/lib/supabase-server";
import type { Json } from "@/lib/database.types";

function parseJson(text: string) { return JSON.parse(text.replace(/^```(?:json)?/i, "").replace(/```$/i, "").trim()) as Record<string, unknown>; }

export async function POST(request: NextRequest, context: { params: Promise<{ id: string }> }) {
  const user = await getCurrentUser(); if (!user) return NextResponse.json({ error: "Sign in first." }, { status: 401 }); const { id } = await context.params; const body = await request.json().catch(() => null) as { kind?: string } | null; if (body?.kind !== "cards" && body?.kind !== "quiz") return NextResponse.json({ error: "Choose flashcards or quiz." }, { status: 400 });
  const admin = createAdminSupabase(); const { data: material } = await admin.from("study_materials").select("id, subject, extracted_text").eq("id", id).eq("user_id", user.id).maybeSingle(); if (!material) return NextResponse.json({ error: "Material not found." }, { status: 404 });
  const access = await consumeAiAction(user.id, `materials_${body.kind}`); if (!access.allowed) return NextResponse.json({ error: "Your included AI actions are used. Upgrade to generate more practice." }, { status: 402 });
  const cards = body.kind === "cards"; const instruction = cards ? "Return strict JSON: {\"flashcards\":[{\"question\":\"\",\"answer\":\"\",\"topic\":\"\"}]}. Create exactly 10 concise active-recall cards." : "Return strict JSON: {\"questions\":[{\"question\":\"\",\"options\":[\"\",\"\",\"\",\"\"],\"correctIndex\":0,\"explanation\":\"\"}]}. Create exactly 6 questions with one unambiguous correct answer.";
  const completion = await new Groq({ apiKey: process.env.GROQ_API_KEY }).chat.completions.create({ model: "llama-3.3-70b-versatile", temperature: 0.25, max_tokens: 1800, response_format: { type: "json_object" }, messages: [{ role: "system", content: `You create Leaving Cert study practice from the student's notes only. Do not invent claims not supported by the notes. ${instruction}` }, { role: "user", content: `Subject: ${material.subject}\n\nNOTES:\n${material.extracted_text.slice(0, 16000)}` }] });
  const parsed = parseJson(completion.choices[0]?.message?.content ?? "{}");
  if (cards) { const values = Array.isArray(parsed.flashcards) ? parsed.flashcards.slice(0, 10) : []; if (!values.length) return NextResponse.json({ error: "No flashcards were generated." }, { status: 502 }); await admin.from("flashcards").delete().eq("material_id", id).eq("user_id", user.id); const rows = values.map((value) => { const item = value as Record<string, unknown>; return { material_id: id, user_id: user.id, question: String(item.question ?? "").slice(0, 500), answer: String(item.answer ?? "").slice(0, 1000), topic: String(item.topic ?? material.subject).slice(0, 80) }; }).filter((item) => item.question && item.answer); const { data, error } = await admin.from("flashcards").insert(rows).select("id, question, answer, topic, confidence"); if (error) return NextResponse.json({ error: "Flashcards could not be saved." }, { status: 500 }); return NextResponse.json({ flashcards: data, remaining: access.remaining ?? null }); }
  const values = Array.isArray(parsed.questions) ? parsed.questions.slice(0, 6) : []; if (!values.length) return NextResponse.json({ error: "No quiz was generated." }, { status: 502 }); await admin.from("quiz_questions").delete().eq("material_id", id).eq("user_id", user.id); const rows = values.map((value) => { const item = value as Record<string, unknown>; const options = Array.isArray(item.options) ? item.options.slice(0, 4).map(String) : []; return { material_id: id, user_id: user.id, question: String(item.question ?? "").slice(0, 700), options: options as Json, correct_index: Math.max(0, Math.min(3, Number(item.correctIndex ?? 0))), explanation: String(item.explanation ?? "").slice(0, 1000) }; }).filter((item) => item.question && Array.isArray(item.options) && item.options.length === 4); const { data, error } = await admin.from("quiz_questions").insert(rows).select("id, question, options, correct_index, explanation"); if (error) return NextResponse.json({ error: "Quiz could not be saved." }, { status: 500 }); return NextResponse.json({ quiz: data, remaining: access.remaining ?? null });
}
