import Link from "next/link";

export const metadata = {
  title: "Terms of Service — StudyWith",
  description: "The terms and conditions governing use of StudyWith.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#FDFCF8]">
      <div className="max-w-3xl mx-auto px-6 py-16 md:py-24">
        <Link href="/" className="text-sm text-[#57534E] hover:text-[#1A1A1A] transition-colors mb-10 inline-block">
          ← Back to home
        </Link>

        <h1 className="font-serif text-4xl font-medium text-[#1A1A1A] mb-2">Terms of Service</h1>
        <p className="text-sm text-[#A8A29E] mb-12">Last updated: March 2026</p>

        <div className="prose prose-stone max-w-none space-y-10 text-[#1A1A1A]">

          <section>
            <h2 className="font-serif text-2xl font-medium mb-4">1. Acceptance of terms</h2>
            <p className="text-[#57534E] leading-relaxed">
              By creating an account or using StudyWith, you agree to these Terms of Service. If you do not agree, do not use the service. These terms form a binding agreement between you and StudyWith. We may update these terms from time to time. Continued use of the service after an update constitutes acceptance of the revised terms.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-medium mb-4">2. The service</h2>
            <p className="text-[#57534E] leading-relaxed">
              StudyWith provides an AI-powered Socratic tutoring service. The service is designed to help you learn by guiding your thinking rather than providing direct answers. The AI tutor is not a substitute for professional academic advice, a qualified teacher, or formal education. Responses generated by the AI may occasionally contain errors, and you should apply your own judgement when reviewing them.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-medium mb-4">3. Accounts</h2>
            <p className="text-[#57534E] leading-relaxed mb-3">
              You must provide accurate information when creating your account and keep your login credentials secure. You are responsible for all activity that takes place under your account. You must:
            </p>
            <ul className="space-y-2 text-[#57534E]">
              <li className="flex gap-2"><span className="text-[#D97706] shrink-0">•</span><span>Be at least 13 years old to use the service. If you are under 16, you confirm that you have parental or guardian consent.</span></li>
              <li className="flex gap-2"><span className="text-[#D97706] shrink-0">•</span><span>Not share your account with others.</span></li>
              <li className="flex gap-2"><span className="text-[#D97706] shrink-0">•</span><span>Notify us immediately if you suspect unauthorised access to your account.</span></li>
            </ul>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-medium mb-4">4. Acceptable use</h2>
            <p className="text-[#57534E] leading-relaxed mb-3">You agree not to use StudyWith to:</p>
            <ul className="space-y-2 text-[#57534E]">
              <li className="flex gap-2"><span className="text-[#D97706] shrink-0">•</span><span>Attempt to manipulate, jailbreak, or circumvent the AI tutor&apos;s guidelines.</span></li>
              <li className="flex gap-2"><span className="text-[#D97706] shrink-0">•</span><span>Submit content that is illegal, abusive, hateful, or violates the rights of others.</span></li>
              <li className="flex gap-2"><span className="text-[#D97706] shrink-0">•</span><span>Reverse engineer, scrape, or reproduce any part of the service without permission.</span></li>
              <li className="flex gap-2"><span className="text-[#D97706] shrink-0">•</span><span>Use the service in any way that could harm, disable, or overburden our infrastructure.</span></li>
              <li className="flex gap-2"><span className="text-[#D97706] shrink-0">•</span><span>Impersonate any person or entity, or misrepresent your affiliation with any person or entity.</span></li>
            </ul>
            <p className="text-[#57534E] leading-relaxed mt-3">We reserve the right to suspend or terminate accounts that violate these terms.</p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-medium mb-4">5. Subscriptions and billing</h2>
            <p className="text-[#57534E] leading-relaxed mb-3">
              Access to StudyWith may require a paid subscription. Subscriptions are billed in advance on a monthly or annual basis. All payments are processed securely by Stripe.
            </p>
            <ul className="space-y-2 text-[#57534E]">
              <li className="flex gap-2"><span className="text-[#D97706] shrink-0">•</span><span><strong className="text-[#1A1A1A]">Free trial:</strong> Where offered, a free trial gives you full access for a limited period. Your card is charged automatically when the trial ends unless you cancel beforehand.</span></li>
              <li className="flex gap-2"><span className="text-[#D97706] shrink-0">•</span><span><strong className="text-[#1A1A1A]">Cancellation:</strong> You can cancel your subscription at any time from your account settings. Access continues until the end of the current billing period. No refunds are issued for partial periods.</span></li>
              <li className="flex gap-2"><span className="text-[#D97706] shrink-0">•</span><span><strong className="text-[#1A1A1A]">Price changes:</strong> We will give at least 30 days notice before any price change takes effect for existing subscribers.</span></li>
            </ul>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-medium mb-4">6. Intellectual property</h2>
            <p className="text-[#57534E] leading-relaxed">
              The StudyWith service, including its design, branding, and underlying code, is owned by us and protected by intellectual property law. You retain ownership of the content you submit (your assignments and messages). By submitting content, you grant us a limited licence to process and store it solely for the purpose of delivering the service to you.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-medium mb-4">7. Disclaimer of warranties</h2>
            <p className="text-[#57534E] leading-relaxed">
              StudyWith is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind. We do not guarantee that the service will be uninterrupted, error-free, or that AI-generated responses will be accurate, complete, or suitable for any particular academic purpose. Use of the service is at your own discretion and risk.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-medium mb-4">8. Limitation of liability</h2>
            <p className="text-[#57534E] leading-relaxed">
              To the fullest extent permitted by law, StudyWith shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the service, including but not limited to academic outcomes, lost data, or service interruptions. Our total liability to you for any claim arising out of or relating to these terms or the service shall not exceed the amount you paid us in the 12 months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-medium mb-4">9. Termination</h2>
            <p className="text-[#57534E] leading-relaxed">
              You may close your account at any time via Settings. We reserve the right to suspend or terminate your access at any time if you breach these terms or if we discontinue the service, with or without notice. Upon termination, your right to use the service ends immediately.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-medium mb-4">10. Governing law</h2>
            <p className="text-[#57534E] leading-relaxed">
              These terms are governed by the laws of Ireland. Any disputes shall be subject to the exclusive jurisdiction of the Irish courts, except where mandatory consumer protection laws in your country of residence provide otherwise.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl font-medium mb-4">11. Contact</h2>
            <p className="text-[#57534E] leading-relaxed">
              For any questions about these terms, contact us at{" "}
              <a href="mailto:hello@studywith.app" className="text-[#D97706] hover:underline">hello@studywith.app</a>.
            </p>
          </section>

        </div>
      </div>
    </div>
  );
}
